name: Staging Deploy
description: "Staging Deploy"
inputs:
  url-prefix:
    description: "URL Prefix"
    required: true
  env:
    description: "Environment"
    required: true
runs:
  using: "composite"
  steps:
    - id: deploy
      run: |
        sudo snap install yq
        export URL_PREFIX=${{ inputs.url-prefix }}
        yq eval -i '.app.versions += [env(URL_PREFIX)'] superhero-ui/values-${{ inputs.env }}
        if [ ${{ inputs.env }}  != "prd" ]; then 
            yq eval -i '.app.ingress.hosts += [{"host": "'${URL_PREFIX}'.${{ inputs.env }}.aepps.com", "paths": { "path": "/"}}]' superhero-ui/values-${{ inputs.env }}
            yq eval -i '.. style="double"' superhero-ui/values-${{ inputs.env }}
        else
            :
        fi
        cat superhero-ui/values-${{ inputs.env }}
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Deploy ${URL_PREFIX}.${{ inputs.env }}.aepps.com"
      shell: bash
