name: Staging Deploy
description: "Staging Deploy"
inputs:
  url-prefix:
    description: "URL Prefix"
    required: true
  env:
    description: "Environment"
    required: true
  app:
    description: "App"
    required: true
runs:
  using: "composite"
  steps:
    - id: deploy
      run: |
        sudo snap install yq
        export URL_PREFIX=${{ inputs.url-prefix }}
        yq eval -i '.app.versions += [env(URL_PREFIX)'] ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        if [ ${{ inputs.env }}  != "prd" ]; then 
            yq eval -i '.app.ingress.hosts += [{"host": "'${URL_PREFIX}'.${{ inputs.env }}.aepps.com", "paths": { "- path": "/"}, "paths": {"  version": "${URL_PREFIX}"}}]' ${{ inputs.app }}/values-${{ inputs.env }}.yaml
            sed -i.bak "s/'//g" ${{ inputs.app }}/values-${{ inputs.env }}.yaml
            rm -rf ${{ inputs.app }}/values-${{ inputs.env }}.yaml.bak
            yq eval -i '.. style="double"' ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        else
            :
        fi
        cat ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Deploy pr-${URL_PREFIX}.${{ inputs.env }}.aepps.com"
      shell: bash
