name: Staging Deploy
description: "Staging Deploy"
inputs:
  pr-number:
    description: "PR Number"
    required: true
  env:
    description: "Environment"
    required: true
runs:
  using: "composite"
  steps:
    - id: deploy
      run: |
        sudo snap install yq
        export PR_NUMBER=${{ inputs.pr-number }}
        export FULL_PR_NUMBER="pr-$PR_NUMBER"
        yq eval -i '.app.versions += [env(FULL_PR_NUMBER)'] superhero-ui/values-staging.yaml
        yq eval -i '.app.ingress.hosts += [{"host": "'${FULL_PR_NUMBER}'.${{ inputs.env }}.aepps.com", "paths": { "path": "/"}}]' superhero-ui/values-staging.yaml
        yq eval -i '.. style="double"' superhero-ui/values-staging.yaml
        cat superhero-ui/values-staging.yaml
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Deploy ${FULL_PR_NUMBER}.${{ inputs.env }}.aepps.com"
      shell: bash
