name: Staging Deploy
description: "Staging Deploy"
inputs:
  url-prefix:
    description: "URL Prefix"
    required: true
  env:
    description: "Environment"
    required: true
runs:
  using: "composite"
  steps:
    - id: deploy
      run: |
        sudo snap install yq
        export URL_PREFIX=${{ inputs.url-prefix }}
        yq eval -i 'del( .app.versions[] | select(. == env(URL_PREFIX))  )' superhero-ui/values-${{ inputs.env }}.yaml
        yq eval -i 'del(... | select(.[] == "'${URL_PREFIX}.${{ inputs.env }}.aepps.com'"))' superhero-ui/values-${{ inputs.env }}.yaml
        cat superhero-ui/values-${{ inputs.env }}.yaml
      shell: bash
